name: ali_wed_invitation
description: "Ali & Fathima Waleema Wedding Invitation"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#feb800"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/

  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
          weight: 400
        - asset: assets/fonts/ScheherazadeNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ScheherazadeNew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
